image: node:6

stages:
  - build
  - deploy

build:
  artifacts:
    paths:
      - public/
  before_script:
    - npm install
  cache:
    paths:
      - .gitbook/
      - node_modules/
      - ${HOME}/.yarn-cache
      - ${HOME}/.npm
  script:
    - npm run build
  stage: build
  variables:
    GITBOOK_DIR: ".gitbook"

pages:
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - master
  stage: deploy
  script:
    - echo "Already built"
