image: node:6

stages:
  - build
  - publish

build:
  before_script:
    - npm install
  cache:
    paths:
      - node_modules/
      - .gitbook/
  script:
    - npm run build
  stage: build
  variables:
    GITBOOK_DIR: ".gitbook"

pages:
  script:
    - echo "Already built"
  artifacts:
    paths:
      - public
  only:
    - master@hutson/configuration
  stage: publish
  when: on_success
