image: node:6

stages:
  - build
  - publish

build:
  artifacts:
    paths:
      - public/
  before_script:
    - npm install
  cache:
    paths:
      - node_modules/
      - .gitbook/
  script:
    - npm run build
  stage: build
  variables:
    GITBOOK_DIR: ".gitbook"

pages:
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - master@hutson/configuration
  stage: publish
  script:
    - echo "Already built"
  when: on_success
