name: CI
on:
  push:
    branches:
      - '**'
jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    container: koalaman/shellcheck-alpine:v0.7.0
    steps:
      - uses: actions/checkout@v1.2.0
      - run: bash test.sh
